CREATE DATABASE IF NOT EXISTS VetSpa;

USE VetSpa;

CREATE TABLE IF NOT EXISTS DISTRITO (
	CODDIST	CHAR(3) PRIMARY KEY,
	NOMDIST VARCHAR(300)
);

CREATE TABLE IF NOT EXISTS Usuario(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	USERNAME VARCHAR(300),
	PASS VARCHAR(300),
	UNIQUE(USERNAME)
);

CREATE TABLE IF NOT EXISTS Cliente(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	DNICLI CHAR(8) NOT NULL,
	NOMCLI VARCHAR(300),
	NOMSEGCLI VARCHAR(300),
	APEPATCLI VARCHAR(300),
	APEMATCLI VARCHAR(300),
	FECNACCLI DATETIME,
	SEXCLI BOOLEAN,
	CELCLI VARCHAR(10),
	DIRCLI VARCHAR(200),
	CODDIST CHAR(3),
	UNIQUE(DNICLI),
	FOREIGN KEY(CODDIST) REFERENCES DISTRITO(CODDIST) 
);




